Template injections/README.md
Template injections in jinja2 to read/write remote files and get remote code execution.
=> Add Jinja Template injections

OAuth/README.md
Not sure if it qualifies as a _payload_ but I'll let you be the judge of that :)
=> Add CSRF to OAuth2

File Inclusion - Path Traversal/uploadlfi.py
__string__ is used twice on line 13 but it is never imported.
=> import string in uploadlfi.py

Upload insecure files/Python __init__.py/python-generate-init.py
python2 -c "print(0777 << 16L == 0o777 << 16)"  # True
=> Use octal numbers that work in both Python 2 and 3

SSRF injection/README.md
Wouldn't want anyone to think they can't grow up to be an attacker too! :)
=> Remove gender-specific pronoun for attacker

XSS injection/README.md
https://github.com/danielmiessler/SecLists/edit/master/Fuzzing/Polyglots/XSS-Polyglots.txt
new attack patterns: line 1, 2, 3.
=> add new attack patterns from Daniel miessler

Upload insecure files/PHP .htaccess/README.md
1. Added one yet image type,
2. Added PoCs.
=> Update exif_imagetype bypass

README.md
Fixed Hack The Box-Link so that it is now cliackable
=> Fixed Hack The Box-Link

XSS injection/README.md
Added new ECMAScript6 XSS bypass variant and fixed a payload missing `/` in `</script>`.
=> Added a new bypass variant + fixed a payload

GraphQL Injection/README.md
Following the directory and text structure of the project, I have added a few notes regarding GraphQL injection. References are added, that point to documentation for GraphQL inner workings.
=> Added GraphQL injection notes

Server Side Request Forgery/README.md
Minor change to fix broken links within the page
=> Fix anchors in README.md

Insecure Deserialization/PHP.md
Added below write-up of kaspersky CTF:
https://medium.com/@jaimin_gohel/ctf-writeup-php-object-injection-in-kaspersky-ctf-28a68805610d
=> Added CTF writeup in reference section

SQL Injection/README.md
admin' -- - (variant of pre-existing)
=> Add authentification bypass

Methodology and Resources/Reverse Shell Cheatsheet.md
Added a reverse shell created with Golang
=> Reverse shell Golang

Methodology and Resources/Windows - Privilege Escalation.md
=> Update Windows - Privilege Escalation.md

Methodology and Resources/Linux - Privilege Escalation.md
Adding a tool that helps with privilege escalation on linux through SUDO.
=> Update Linux - Privilege Escalation.md

Open Redirect/README.md
Add Host/Split Exploitable Antipatterns in Unicode Normalization BH 2019 for filter bypass
=> Add Host/Split Unicode Normalization

XXE Injection/README.md
Source: https://portswigger.net/web-security/xxe/lab-xxe-via-file-upload
=> Add XXE payload inside SVG

Methodology and Resources/Network Discovery.md
1. spyse itself 
2. python wrapper - using only a part of the available functionality of spyse, but will be updated very soon.
=> Add Spyse to network discovery

NoSQL Injection/README.md
- fix exploits ToC anchor
- add nosqlilab
=> little changes

Kubernetes/readme.md
=> Add Kubernetes file

Methodology and Resources/Active Directory Attack.md
If you already have the NTLM hash of the account, it doesn't need to be cracked.
=> Update Silver Ticket

XSS Injection/Intruders/jsonp_endpoint.txt
Added 3 yahoo jsonp endpoints
* https://ads.yap.yahoo.com/nosdk/wj/v1/getAds.do?cb=alert(1337)
* https://mempf.yahoo.co.jp/offer?position=h&callback=alert(1337)
* https://suggest-shop.yahooapis.jp/Shopping/Suggest/V1/suggester?callback=alert(1)//&appid=dj0zaiZpPVkwMDJ1RHlqOEdwdCZzPWNvbnN1bWVyc2VjcmV0Jng9M2Y-
=> Added 3 yahoo jsonp endpoints

SQL Injection/PostgreSQL Injection.md
Updated PostgreSQL Error Based injections
=> Update PostgreSQL Injection.md

SQL Injection/PostgreSQL Injection.md, XSS Injection/README.md
* PostgreSQL version
* PostgreSQL Current User
* PostgreSQL List Users
* PostgreSQL List Password Hashes
* PostgreSQL List Privileges
* PostgreSQL database name
* PostgreSQL List databases
* PostgreSQL List tables
* PostgreSQL List columns
* PostgreSQL Stacked query
=> Added More PostgreSQL Injection Queries And Blind XSS endpoint

SQL Injection/README.md
=> Add bypass WAF no equal using BETWEEN

SQL Injection/PostgreSQL Injection.md
```sql
SELECT usename FROM pg_user WHERE usesuper IS TRUE
```
=> Added List Database Administrator Accounts

NoSQL Injection/README.md
For cases when correct POST'd details causes a page redirect instead of just displaying an 'OK' message
=> Added an alternate possible Found condition to POST

XSS Injection/README.md
Bypass XSS filters using javascript global variables based on the following article https://www.secjuice.com/bypass-xss-filters-using-javascript-global-variables/ from theMiddle.
=> Bypass XSS filters on alert

XSS Injection/XSS in Angular.md
great resource, I have found it very helpful thanks.
I've created this PR to clarify what is related to AngularJS vs Angular, as the XSS issues in these two framework major versions are very different between AngularJS(1.x.x) and Angular(2+)
=> clarify AngularJS vs Angular

API Key Leaks/README.md
=> Fixed Broken Links in API Key Leaks

CSRF Injection/README.md
=> Updated Summary and Fixed  Broken Links in CSRF

Directory Traversal/README.md
=> Fixed Broken Links in Directory traversal

Command Injection/Intruder/command-execution-unix.txt
We must check inner double or single quote case
=> Add escaped double or single quote cases

Methodology and Resources/Reverse Shell Cheatsheet.md
Made the command to use python3 because mostly now the machines have python3 installed.
=> Update TTY shell command for python

Methodology and Resources/Reverse Shell Cheatsheet.md
Added threading shells and alternative pure Java reverse shell
=> Updated Java & Groovy Shells

File Inclusion/README.md
=> Update File Inclusion

SQL Injection/MySQL Injection.md
MySQL Blind Queries and Data Exfiltration via the ORDER BY clause.
=> Blind SQL Injection payloads missing from the website.

Server Side Template Injection/README.md
Simple improvements to Jinja2 SSTI RCE to clean up the "0"s in output and facilitate the command input field.
=> Improvement to the SSTI RCE

Server Side Request Forgery/README.md
=> Update AWS SSRF tips

Methodology and Resources/Windows - Privilege Escalation.md
Added `cmd \c C:\Users\nc.exe` as not typing `cmd \c` did not work for me. Might need even more explanation
=> added cmd on the USOSVC vuln

SQL Injection/SQLite Injection.md
Added new link location for the pdf.
=> Update SQLite Injection.md

Web Sockets/README.md
Hi
This adds Cross-Site WebSocket Hijacking (CSWSH).
Cool repo btw :)
Best regards,
Emanuel
=> Added: Cross-Site WebSocket Hijacking (CSWSH)

CORS Misconfiguration/README.md
Added other CORS misconfigurations:
* Null Origin Allowed
* XSS on trusted Origin
* Wildcard Origin allowed
Best,
Emanuel
=> Added: Other CORS Misconfigurations

Server Side Template Injection/README.md
Made a quick modification to add credits.
=> Added RCE SSTI Jinja2 Bypass payload developed by SecGus (chivato)

Methodology and Resources/Reverse Shell Cheatsheet.md
Add others shell on reverse shell cheatsheet
=> Add others shell on reverse shell cheatsheet

YOUTUBE.md
I have added the Hacksplained Youtube channel to the list of channels in the Youtube section.
=> added Hacksplained's YT channel

Server Side Template Injection/README.md
learned from Port Swigger Web Security
ref: https://portswigger.net/web-security/server-side-template-injection/exploiting/lab-server-side-template-injection-basic
=> Adding Execute code using SSTI for ERB engine in SSTI vulnerability payload

Upload Insecure Files/README.md
=> Adding the solution of Magic Bytes in the Unrestricted File Upload section

Server Side Template Injection/README.md
=> Update ERB SSTI tips

Command Injection/README.md
added the results of echo and tr commands for clarification
=> clarification in 'bypass character filter'

Server Side Request Forgery/README.md
```
$ dig +short metadata.nicob.net
...
```
Not resolving
=> metadata.nicob.net not long resolve to metadata IP

XXE Injection/README.md
- Add new refs
- Format title with date, author, etc.
- Remove dead hosts:
- agrawalsmart7.com
- esoln.net
=> XXE ref. refactor

Directory Traversal/README.md
Adding always existing file in recent Windows machine. Ideal to test path traversal but nothing much interesting inside
=> Add useful always existing windows file

YOUTUBE.md
Hey there,
I have added many more English youtube channels and created the Hindi youtube channels category. Also, I have added Defcon 2020 talks and have included the legendary hacker manifesto by the mentor. Please review the PR and if you merge it, please add the `hacktoberfest-accepted` label. Thank you
=> Added YouTube Channels 

SQL Injection/MSSQL Injection.md
Broken link [Sqlinjectionwiki - MSSQL](http://www.sqlinjectionwiki.com/categories/1/mssql-sql-injection-cheat-sheet/) .
=> Update MSSQL Injection.md

SQL Injection/Cassandra Injection.md
Broken link [https://hack2learn.pw/cassandra/login.php](https://hack2learn.pw/cassandra/login.php)
=> Update Cassandra Injection.md

Methodology and Resources/Network Pivoting Techniques.md
Same method like ngrok but with CloudFlare servers,
Abuse the unauthenticated free try of CloudFlare Argo tunnel
=> Use cloudflared to expose internal services

CVE Exploits/README.md
- Add EternalBlue and BlueKeep CVEs
- Move Heartbleed and Shellshock in the "older" section since they were found more than 5 years ago
=> Update big CVEs list

CORS Misconfiguration/README.md, CRLF Injection/README.md
I did a bit of research on CORS and CRLF and thought I'd update the documentation in this repo. If you have further questions regarding the content feel free to ask me.
=> CORS and CRLF documentation updated

Insecure Deserialization/Java.md
Adding marshalsec tool & references
=> Adding marshalsec tool & references

XSS Injection/README.md
Hey,
I saw that the `README.md` contains many tools for monitoring Blind XSS but no suggestions for tools that could be used to exploit or identify this vulnerability. Therefore I added the most important ones. If I still forgot anything, just add it. 
Thanks
=> XSS detection tools added

Methodology and Resources/Linux - Privilege Escalation.md
I added more information on kernel exploits, how to obtain your kernel version and distro and search for a kernel exploit accordingly.
=> Added more information on kernel exploits

Methodology and Resources/Linux - Privilege Escalation.md
I very strongly recommend adding LinPEAS to the enumeration tools. LinPEAS is arguably the best linux privesc enumeration tool out there. If you haven't used it, I'd try it out. It highlights all relevant information with color coded text, and you can pass it parameters to control the thoroughness of the scan. I should add WinPEAS for windows privesc as well.
=> Added LinPEAS to Linux Privesc.

Methodology and Resources/Windows - Privilege Escalation.md
WinPEAS is a really thorough privesc enumeration tool for windows, you can find it here: https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite/tree/master/winPEAS/winPEASexe
It doesn't auto exploit, but it's rather thorough and effective.
=> Added winPEAS to windows privilege escalation tool

SQL Injection/MySQL Injection.md
Please refer to this [link's](https://portswigger.net/web-security/sql-injection/cheat-sheet) comments section.
=> Update MySQL Injection.md

Server Side Template Injection/README.md
=> Improved Jade payload

TWITTER.md
Hi, 
since a large part of the infosec community is exchanging news on twitter, i thought that the most important accounts should not be missing in this repo. I know that the list is far from complete but at least it is a start. 
Feel free to add accounts as well.
=> TWITTER.md added

AWS Amazon Bucket S3/README.md, Methodology and Resources/Cloud - AWS Pentest.md
A useful tool to check permissions on s3 buckets during whitebox assessments. It requires an aws profile that actually has access to the s3 buckets/objects in order to check for any authentication issues.
=> Add tool nccgroup/s3_objects_check

Insecure Source Code Management/README.md
Another tool to recover .git directories
=> Add tool GitTools

File Inclusion/README.md, Insecure Source Code Management/README.md
=> Add reference to panoptic and rip-hg tools

Methodology and Resources/Methodology and enumeration.md
Minor fixes. The link to the original WAHH Task Checklist on mdsec.net is now dead.
=> Fix links and duplicated nmap and massscan examples

Kubernetes/readme.md, Request Smuggling/README.md
Added kube-hunter after reading about it on https://labs.bishopfox.com/industry-blog/pen-testing-tools-were-thankful-for-in-2020
=> Add tools kube-hunter and smuggler

API Key Leaks/README.md, AWS Amazon Bucket S3/README.md, Methodology and Resources/Cloud - AWS Pentest.md
- cleaned up the Cloud AWS methodo
- added the `dufflebag` tool
=> Update Cloud AWS Methodology

Insecure Deserialization/Java.md
Cleaned up the Java Deserialization page and added gdgetprobe
=> Add tool gadgetprobe

HTTP Parameter Pollution/README.md
Adding this reference here since it is a neat trick in bypassing multi-layered web applications.
=> Created HTTP Parameter Pollution

XSS Injection/README.md
Yeah I know it is logic to use it if you really need the closing tag. But having both brackets in your repo makes it quicker to copy paste :D
=> Added closing bracket in unicode full width bypass

Kubernetes/readme.md
$subject and minor correction of a file path
=> Add Kubernetes Pentest Methodology Part 3

SQL Injection/PostgreSQL Injection.md
=> Add PostgreSQL Check if Current User is Supperuser

API Key Leaks/README.md
=> API Key Leaks: Added commands for testing Mapbox API Tokens

XXE Injection/README.md
I've only ever tried this once, against the java XML parser.
Kinda based upon the suggestion here, but required some tweaking to get to work.
https://phonexicum.github.io/infosec/xxe.html#dtd-attack-vectors
=> Add XXE via DTD file

SQL Injection/PostgreSQL Injection.md
Small PR with a little more succinct way to write to a file in Postgres.
=> Add a one line postgres file write

Insecure Source Code Management/README.md
This tool was featured numerous times in [ippsec's](https://www.youtube.com/channel/UCa6eh7gCkpPo5XXUDfygQQA) hackthebox.eu walkthroughs so i thought i'd add it to the list :)
=> New tool git-dumper.py

Methodology and Resources/Linux - Privilege Escalation.md
=> [typo] changed sshs_config to sshd_config

Methodology and Resources/Windows - Mimikatz.md
Leaving the lsass unprotected is maybe not a good idea ;)
https://github.com/gentilkiwi/mimikatz/blob/fe4e98405589e96ed6de5e05ce3c872f8108c0a0/mimikatz/modules/kuhl_m_kernel.c#L99
=> Add mimikatz command to protect a process after removing the protection

Methodology and Resources/Reverse Shell Cheatsheet.md
- Declared variables
- Added semicolons at the end of each line
- Fixed the bash command
=> Fix Java payload (issue #337)

CSV Injection/README.md
=> Added additional CSV injection cases patterned after in the wild samples

Upload Insecure Files/Extension ASP/shell.ashx
Added .ashx extension shell for Upload Insecure Files (ASP)
=> Add .ashx shell

Methodology and Resources/Reverse Shell Cheatsheet.md
Added: Automatic Reverse Shell Generator
=> Update Reverse Shell Cheatsheet.md

Methodology and Resources/Cloud - AWS Pentest.md
Some DynamoDB enumeration with aws CLI.
Commands have been used to complete the Bucket HTB box.
=> Add AWS DynamoDB enumeration

JSON Web Token/README.md
=> Updates JWT tool

Server Side Template Injection/README.md
Add more example for Smarty Template Injection compatible with the version 3
=> Update Smarty Template Injection

NoSQL Injection/Intruder/NoSQL.txt
Works for `User.findOne({ payload })` in Nodejs Express mongoose
=> add NoSQLi payload

Command Injection/README.md
Fix snippets in Command Injection.
=> Fix snippets

XSS Injection/README.md
=> XSS: remove bluelotus

Server Side Request Forgery/README.md
Credits to this tweet: https://twitter.com/Random_Robbie/status/1268186743657947137
=> Add AWS SSRF Bypasses

CSRF Injection/README.md
Hi, I added referer header validation check in CSRF and fixed typo 😁
I added it because it's necessary for CSRF payload. and let me know if it's weird.
=> Added referer header validation check in CSRF

Methodology and Resources/Reverse Shell Cheatsheet.md
Added Reverse Shell using Telnet.
=> Added Reverse Shell using Telnet

Server Side Template Injection/README.md
Added Lessjs example PoC and reference link to advisory blog post
=> Adds Lessjs injections

Methodology and Resources/Reverse Shell Cheatsheet.md
-Revised existing Linux Python Reverse Shells
-Added New Linux Python Reverse Shells
=> New/Updated Python Linux Reverse Shells

XSS Injection/README.md
Added <object/data="jav&#x61;sc&#x72;ipt&#x3a;al&#x65;rt&#x28;23&#x29;"> XSS payload
=> Added XSS <object> payload

Server Side Template Injection/README.md
Added shorter payloads for Server Side Template injections in jinja2
=> Added shorter payloads for Server Side Template injections in jinja2

Command Injection/README.md, LaTeX Injection/README.md
Added missing descriptions and fixed color formatting for LaTeX
=> Added missing descriptions and fixed color formatting for LaTeX

Methodology and Resources/Active Directory Attack.md
Add Linux alternatives for GenericWrite abuse using the Samba software suite:
-  `rpcclient` to change the password of another user
-  `net rpc` to add a user to an AD group using RPC
=> Add Linux alternatives for GenericWrite abuse

Methodology and Resources/Active Directory Attack.md
Add python check for ZeroLogon using the script written by Secura
=> Add python check for ZeroLogon

SQL Injection/OracleSQL Injection.md
Add some error point oracle sql injection
=> Update Oracle Sql injection.md add sql error

SQL Injection/README.md
- Whitespace alternatives
- The list of whitespaces characters alternatives  is taken directly from [SQLi-Optimization-and-Obfuscation...]
- WAF Bypasses
- The list of obfuscated queries is also taken directly from [SQLi-Optimization-and-Obfuscation...](https://paper.bobylive.com/Meeting_Papers/BlackHat/USA-2013/US-13-Salgado-SQLi-Optimization-and-Obfuscation-Techniques-Slides.pdf)
*Disclaimer: From the two references added, I co-authored one ([Scientific Notation Bug in MySQL...](https://www.gosecure.net/blog/2021/10/19/a-scientific-notation-bug-in-mysql-left-aws-waf-clients-vulnerable-to-sql-injection/)).*
=> SQL injection various additions

Kubernetes/readme.md
kubescape is a relatively new open-source tool for testing if Kubernetes is deployed securely according to multiple frameworks: regulatory, customized company policies and DevSecOps best practices, such as the NSA-CISA and the MITRE ATT&CK®.
link to repo: https://github.com/armosec/kubescape
=> Add kubescape to kubernetes tools

Methodology and Resources/Reverse Shell Cheatsheet.md
Delete unused imports in cheatsheet reverse shell.
=> Delete unused import

Server Side Request Forgery/README.md
=> Replace xip.io by nip.io

SQL Injection/SQLite Injection.md
I've added a very useful SQLite injection used to extract the database structure, in the normal SQL format.
=> SQLite Injection add extract database structure

Methodology and Resources/Hash Cracking.md
Hey 👋 
Updating content with more information and more accurate resources.
=> Update Hash Cracking.md

Methodology and Resources/Active Directory Attack.md
Correcting typo
Removing dead website
Adjusting techniques
=> Update Active Directory Attack.md

Methodology and Resources/Reverse Shell Cheatsheet.md
=> add tools section

LaTeX Injection/README.md
add `\catcode` to disable LaTex control characters
=> LaTeX Injection catcode

Methodology and Resources/Cobalt Strike - Cheatsheet.md
Update Cobalt Strike user Guide to the latest version.
=> Update Cobalt Strike - Cheatsheet.md

Methodology and Resources/Cloud - AWS Pentest.md
Added a reference to Cloudgoat in the Training section of the AWS pentesting docs.
=> Update Cloud - AWS Pentest.md

Methodology and Resources/Linux - Privilege Escalation.md
Fixed some links in the table of contents
=> Added DirtyPipe to kernel exploits

Web Sockets/README.md
Hello ! 
Noticed a syntax error for the CSWSH payload
=> Update CSWSH payload

Server Side Template Injection/README.md
Hi, adding a polyglot payload for SSTI detection along with the resource I found it in.
=> Add SSTI detection payload + related resource

Server Side Template Injection/README.md
Adding variable expressions alternative for java injection
=> Update Java SSTI

XSS Injection/XSS in Angular.md
Added payload bypass Waf [Imperva]:
Proof of payload:
```
https://portswigger-labs.net/xss/angularjs.php?type=reflected&csp=0&version=1.6.0&x={{x=[%27constr%27,%20%27uctor%27];a=x.join(%27%27);b={};a.sub.call.call(b[a].getOwnPropertyDescriptor(b[a].getPrototypeOf(a.sub),a).value,0,%27pr\\u{6f}mpt(d\\u{6f}cument.d\\u{6f}main)%27)()}}
```
=> [update] Angular XSS payload

SQL Injection/PostgreSQL Injection.md
I was searching for some postgresql time based payloads a few days ago for database,table,columns extract in the [sql injection postgresql](https://github.com/swisskyrepo/PayloadsAllTheThings/blob/master/SQL%20Injection/PostgreSQL%20Injection.md) topic but I didn't find anything so I decided to put some of my own.
=> Update the Postgresql time based payloads for database,table,columns extract

XSS Injection/README.md
Adding XSS brutelogic polyglot from blog post.
=> XSS: Adding brutelogic polyglot

Methodology and Resources/Windows - Mimikatz.md
hekatomb is now available on pypi to simplify its installation
=> update hekatomb to install with pip

NoSQL Injection/README.md
- add missing menu item
- use better string interpolation for python script
- add ruby script
=> Blind NoSQL scripts

Account Takeover/README.md, CORS Misconfiguration/README.md, CRLF Injection/README.md, CSRF Injection/README.md, Directory Traversal/README.md, Insecure Deserialization/README.md, Insecure Direct Object References/README.md, JSON Web Token/README.md, OAuth/README.md, Open Redirect/README.md, SQL Injection/README.md, Server Side Request Forgery/README.md, Upload Insecure Files/README.md, Web Cache Deception/README.md, Web Sockets/README.md, XSS Injection/README.md, XXE Injection/README.md
=> Added PortSwigger Labs to the repo

Insecure Deserialization/PHP.md, Methodology and Resources/Active Directory Attack.md, README.md, Server Side Template Injection/README.md
Forcing output on blind RCE in Jinja template injections
=> Blind SSTI Jinja

Methodology and Resources/Methodology and enumeration.md
Updating methodology to new tools and technologies
=> Methodology and enumeration rework

XXE Injection/README.md
- Add two references: "OWASP XXE prevention cheat sheet" and "XXE: How to become a Jedi"
- Describe the Parameters Laugh attack
- Expand the WAF bypass method with UTF-7
- Update the summary
=> XXE: Improve the documentation

Upload Insecure Files/Zip Slip/README.md
This will add slipit to the "Zip Slip" topic tools, which is a quite nice tool with an extended version of evilarc with some more functionality/documentation.
=> Zip Slip: Add slipit to tools

Command Injection/README.md
Added portswigger labs and reference in Command injection.
=> Added portswigger labs and reference in Command injection

Account Takeover/README.md
Hello Sir,
I have added force browsing the URL to bypass 2FA page method that I found recently on a HackerOne program. There is a similar lab on Portswigger as well. https://portswigger.net/web-security/authentication/multi-factor/lab-2fa-simple-bypass
I hope my pull request will be accepted. If you don't like my PR then please give your feedback.
Regards,
nayeems3c
=> Added 2FA bypass via Force Browsing on Account Takeover branch

Methodology and Resources/Cloud - AWS Pentest.md
Merge the notes with the existing one
=> Merge AWSome Pentesting into Cloud - AWS Pentest

XSS Injection/README.md
Added an alternative to document.cookie for situations when this text is blacklisted.
=> Added document.cookie blacklist bypass

Command Injection/README.md
Small change showing that if you can inject multiple lines, you can run multiple commands.
=> feat: Command injection with newlines

Methodology and Resources/Windows - Privilege Escalation.md
=> Update Windows -Privilege Escalation - Typo Fix

Methodology and Resources/Cloud - AWS Pentest.md
Add explanation for ec2:AssociateIamInstanceProfile.
Also, fix a typo.
=> feat: Explain ec2:AssociateIamInstanceProfile

Methodology and Resources/Linux - Evasion.md
Timestomping is the surruptitious modification of a file's access/modification timestamps.
=> Add timestomping to Linux evasion techniques

Request Smuggling/README.md, Server Side Request Forgery/README.md, Server Side Template Injection/README.md, Upload Insecure Files/README.md, XSS Injection/README.md
Hi, finally I review all links across this documentation, update old links, delete not recoverable links and add new documentation.
Thanks in advance.
=> Review and update documentation

Methodology and Resources/Linux - Persistence.md
Adds information about backdooring git configs and git hooks.
=> Add git persistence techniques

HTTP Parameter Pollution/README.md
=> Add RubyOnRails HTTP Parameter Pollution

Server Side Template Injection/README.md
Hi @swisskyrepo,
I just added in Spring Framework (Java) Server-Side Template Injection detection and exploitation payloads.
Thanks.
=> Added in Spring Framework SSTI Detection & Exploitation

Account Takeover/README.md
- Added helpful tools
- Added a short description
=> Updated Account takeover due to unicode normalization issue

Methodology and Resources/Active Directory Attack.md
Added zerologon authentication relay technique based on [dirkjanm](https://dirkjanm.io/a-different-way-of-abusing-zerologon/) research.
=> Added zerologon authentication relay technique

Insecure Deserialization/PHP.md
fixing domain since the old one got compromised
=> [chore] fix rawsec url

README.md
=> Update sponsor link

SQL Injection/PostgreSQL Injection.md
Switch "column_name" to "table_name".
=> Typo corrections in PostgreSQL Injection.md

Upload Insecure Files/Configuration uwsgi.ini/README.md, Upload Insecure Files/Configuration uwsgi.ini/uwsgi.ini, Upload Insecure Files/README.md
Add a new way to escalate from file upload to RCE using uWSGI configuration file
=> add uwsgi configuration file to Upload Insecure File

File Inclusion/README.md
=> Fix path with sessionS with an S for php

Methodology and Resources/HTML Smuggling.md, Methodology and Resources/Powershell - Cheatsheet.md
On Powershell part:
Refactor sumary with link
Add Win API call through delegation and reflection
Add Basic HTML Smuggling
=> Add Powerhsell Reflection through Delegate Type and Basic HTML Smuggling

Methodology and Resources/Active Directory Attack.md, Methodology and Resources/Network Discovery.md, Methodology and Resources/Office - Attacks.md
On Office, add execution of WinAPI function from VBA (How to import WinAPI function into VBA macro)
On Network Recon,  add network scans with ping and nc
On Active Directory, add inject into AD through relay thanks to ldap signing not required and ldap channel binding not disabled
=> Add some stuff on Office exec, Network Recon and Active Directory methodo

Server Side Template Injection/README.md
Source; https://twitter.com/podalirius_/status/1655970628648697860
=> Adding Jinja2 RCE through lipsum in Templates

Methodology and Resources/Active Directory Attack.md
=> Fixed typos on README.md

Server Side Request Forgery/README.md
Adding one more form of a localhost bypass.
=> SSRF: bypass using IPv6/IPv4 Address Embedding

Methodology and Resources/Active Directory Attack.md, Methodology and Resources/Windows - Using credentials.md
the new supported on official repo is on https://github.com/mpgn/CrackMapExec
=> Use new offical CME repository

Server Side Request Forgery/README.md
Documentation: https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/instancedata-data-retrieval.html
=> Add new AWS IPv6 SSRF Endpoint

LaTeX Injection/README.md
Hi 👋 
Adding a payload to read multi line file.
I also state that injections may need to be wrapped.
Cheers
=> Update README.md for Latex injection

Methodology and Resources/Active Directory Attack.md
Hello,
I allow myself to propose some additions / clarifications concerning the format of NetNTLMv1 tokens, some technical details about their format, and the methods to break them (ShuckNT / Crack.Sh / KPA-attack, etc.).
Hope this can help :)!
Good day,
=> Added precision on the format, generation and breaking of NetNTLMv1

Methodology and Resources/Cloud - AWS Pentest.md
Added `CloudFox` and `CloudFoxable` to the tools/training sections respectively.
=> Added CloudFox and CloudFoxable

Server Side Template Injection/README.md
Added Lodash on the SSTI chapter. All the payloads are tested during the down under ctf 2023.
=> Update Lodash SSTI

Methodology and Resources/Reverse Shell Cheatsheet.md
Simple automatic shell upgrade via rustcat, that's based off commands from conptyshell, sets up the terminal to receive the reverse shell connection, then rustcat will spawn the TTY automatically.
=> Add automatic shell upgrade via rustcat.

SQL Injection/MySQL Injection.md
Add MYSQL Wide byte injection,
it can test in Sqli-labs Less-32,
writeup (chinese): https://www.cnblogs.com/zhengna/p/12660680.html
see: https://github.com/Audi-1/sqli-labs/blob/master/Less-32/index.php
=> Add MYSQL Wide byte injection

API Key Leaks/README.md
=> Fix typo in README.md

GraphQL Injection/README.md
=> Fix typo in GraphQL Injection README.md

XSLT Injection/README.md
Added Execute a remote php file using `file_put_contents`
=> Update README.md (XSLT Injection)

Methodology and Resources/Windows - Privilege Escalation.md
Abusing impersonation privileges through the "Printer Bug" 
article here : https://itm4n.github.io/printspoofer-abusing-impersonate-privileges/
thanks to @itm4n
=> [Add] - Priv esc windows (PrintSpoofer)

Server Side Template Injection/README.md
Both are novel tools to help Pentesters / Bug bounty hunters to detect template injections
=> Added TInjA and the Template Injection Table

Methodology and Resources/Reverse Shell Cheatsheet.md
Reverse shell payload working with OGNL expressions
=> Adding reverse shell payload for OGNL

Methodology and Resources/Windows - Using credentials.md
https://github.com/swisskyrepo/InternalAllTheThings/pull/7
=> switch to nxc as cme is archived

SQL Injection/README.md
Added a section in the README for SQL Injection that showcases how to identify the underlying DBMS (database management system) utilizing the errors that are outputting from sample payloads. This shows the different DBMS, an example payload, and an example of what the error would look like for that DBMS using that payload.
=> DBMS Identification Via Error

Kubernetes/README.md
=> fix:Typo_Fix namespaces

Race Condition/README.md
=> fix:Typo_Race-Condition

CORS Misconfiguration/README.md
Hello,
I've added a new tool, CorsOne, to the PayloadsAllTheThings repository. This tool is designed for identifying and exploiting CORS (Cross-Origin Resource Sharing) misconfigurations.
Details:
Tool Name: CorsOne
Description: CorsOne is a tool designed to quickly and easily detect CORS misconfiguration, compensating for the shortcomings of other tools and providing automatic testing for all relevant cases.
Link: https://github.com/omranisecurity/CorsOne
Thanks,
omranisecurity.
=> Add CorsOne to the Repository

Command Injection/README.md
=> added bypass techniques

Prompt Injection/README.md
This PR adds several new prompt injection techniques relevant to LLMs, categorized under jailbreak, function abuse, prompt masking, etc. These reflect current real-world threats observed in LLM red teaming and testing.
=> Improved Prompt Injection Section with Missing Content
