swisskyrepo/PayloadsAllTheThings

XSS injection/README.md
Actually, is not XSS.
Running scripts like <a href="data:text/html,<script>alert(location.origin)</script>">clickme</a> have location.origin "null".
=> Fix fake xss

XSS Injection/README.md
Found a dead link, it redirects to appio.dev which led me to the new location of the article: https://appio.dev/vulns/google-csp-evaluator/
=> Fixed link for google CSP bypass

Web Sockets/Files/ws-harness.py
Legacy __print__ statements are syntax errors in Python 3 but __print()__ function works as expected in both Python 2 and Python 3.
=> Use print() function in both Python 2 and Python 3

Command Injection/README.md
`host` does not need the `http://` prefix for DNS queries
=> Remove http:// prefix for DNS queries

XSS Injection/README.md
Cloudflare XSS Bypass via add 8 or more superfluous leading zeros for dec and 7 or more for hex.
Dec: `<svg onload=prompt%26%230000000040document.domain)>`
Hex: `<svg onload=prompt%26%23x000000028;document.domain)>`
And another bypass
`xss'"><iframe srcdoc='%26lt;script>;prompt`${document.domain}`%26lt;/script>'>`
=> Cloudflare XSS Bypasses

Server Side Template Injection/README.md
I came across a case where I was unable to use the go to PoC due to an inability to create "tags" (or use spaces) and surprisingly I couldn't find any other PoCs available. 
I modified the original PoC to work without needing those requirements, making it a little more reliable for the case of character sanitization/removal.
=> Added Freemarker SSTI PoC that doesn't require the use of "tags"/spaces

Methodology and Resources/Reverse Shell Cheatsheet.md
The single quotes used in `io.popen` prevent the one-liner from being executed.
This change should fix that :)
=> Fix lua reverse shell quote issue

Methodology and Resources/Reverse Shell Cheatsheet.md
A small typo in the awk one-liner prevents successful execution of the command.
```
awk: cmd. line:1: warning: remote host and port information (10.0.0.1>, 4242) invalid: Name or service not known
awk: cmd. line:1: fatal: can't open two way pipe `/inet/tcp/0/10.0.0.1>/4242' for input/output (No such file or directory)
```
This commit fixes this :)
=> Fix awk snippet

Open Redirect/Intruder/Open-Redirect-payloads.txt
Added new payloads from https://www.hahwul.com/p/ssrf-open-redirect-cheat-sheet.html
Found the following have not been added yet:
http://google.com\www.whitelisteddomain.tld
http://google.com&www.whitelisteddomain.tld
http:///////////google.com
\\google.com
http://www.whitelisteddomain.tld.google.com
=> Added new payloads from hahwul.com

Server Side Request Forgery/README.md
The gopher directive can be used to pass headers, bypassing header security measures for GCP/AWS/Azure.  Although this is somewhat covered in the Gopher HTTP proxy section, I think this clarifies it a bit.
=> Added anti-SSRF header bypass for GCP

Methodology and Resources/Reverse Shell Cheatsheet.md
This reverse shell payload for PHP works even if `exec` is disabled and/or the new socket is not on fd 3
=> Added another PHP reverse shell payload

Methodology and Resources/Reverse Shell Cheatsheet.md
This PR does a bit of cleanup the the 'Methodology and Resources/Reverse Shell Cheatsheet'. 
Port `4242` and IP `10.0.0.1` seems to be the mostly used values across examples. Therefore, changed all other commands to reuse these values. This is done so that I (and others) can easily replace  the value `10.0.0.1` with the desired IP address to change all the commands in one go. 
Additionally, changed commands to use `user@attack` and `user@victim`, across the cheatsheet.
=> Change IP and port to a common value across commands

CVE Exploits/Telerik CVE-2019-18935.py
Adding Telerik exploit for CVE-2019-18935 that is being actively exploited everywhere insecure versions of Telerik are found.
=> add Telerik CVE-2019-18935

File Inclusion/README.md
I originally thought that the `|` was a typo, and that it should be `/`. But from the PHP command line, both seem to work:
```
php > readfile('file');
testhttps://github.com/swisskyrepo/PayloadsAllTheThings/pulls
php > readfile('php://filter/convert.base64-encode/resource=file');
dGVzdAo=
php > readfile('php://filter/convert.base64-encode|convert.base64-encode/resource=file');
ZEdWemRBbz0=
php > readfile('php://filter/convert.base64-encode/convert.base64-encode/resource=file');
ZEdWemRBbz0=
php > readfile('php://filter/zlib.deflate/convert.base64-encode/resource=file');
K0ktLuECAA==
php > readfile('php://filter/zlib.deflate|convert.base64-encode/resource=file');
K0ktLuECAA==
```
However, in a recent OOB XXE I was doing, `/` worked, but `|` didn't. Adding in `/` for completeness.
=> Adding second method of chaining PHP filters

Command Injection/README.md
Hi, your repository is really helpful. Here are some additional bypasses when certain characters are filtered.
=> More Bash tricks to bypass Command Injection filtering

Methodology and Resources/Windows - Privilege Escalation.md
This example was used on hackthebox where it leaked the root flag of a machine on free servers.
This resulted in every user being able to get the root flag before they have even completed the box which isn't fair to others.
This example should either be changed or removed completely to combat copy-pasting without knowing what you're doing.
=> Remove example from win priv esc

Methodology and Resources/Linux - Privilege Escalation.md
\`whoami\` has already been wrapped in backquotes. There is no need to user escape characters again
=> Delete unnecessary escape characters

JSON Web Token/README.md
Before the `JWT token` was being **encoded/decoded** manually. The JWT's module does all that without manual decoding and splitting. 
This PR contains the code to encode the JWT token with type `None` while using `JWT's library` in python.
=> Using JWT's module to encode payload with type `None`

SQL Injection/PostgreSQL Injection.md
These changes add additional information into the Postgres SQLi page. Info on how to read/write files using large objects (getting around the need to be able to `CREATE` or `INSERT`), some extra info on how modern postgres behaves with `pg_read_file` and some additional information on using built in XML helpers for data exfil.
=> Added Postgres SQLi information on xml helpers and file read/write

Server Side Request Forgery/README.md
Added a URL encoding SSRF bypass method and a couple links to PortSwigger's Web Academy, where further details on these vulnerabilities are described.
=> Added SSRF bypass details

XSS Injection/XSS in Angular.md
Added one payload which executes without any usage of (`'`)single-quotes or (`"`)double-quotes. Helpful when you have AngularJS injection but quotes are blocked by the application.
Working proof of payload here: 
https://portswigger-labs.net/xss/angularjs.php?type=reflected&csp=0&version=1.6.0&x={{x=valueOf.name.constructor.fromCharCode;constructor.constructor(x(97,108,101,114,116,40,49,41))()}}
=> [Update] Added 1 payload

Methodology and Resources/Active Directory Attack.md
See https://sensepost.com/blog/2020/ace-to-rce/ for a full explanation.
=> Added GenericWrite example for values used by the Remote Connection Manager.

GraphQL Injection/README.md
The word **quote** was missing. I also added a `'`.
=> Added missing word

Insecure Source Code Management/README.md
It's in the "API Key Leaks" folder now and the content is already present there
=> Remove "Leaked API keys" section

Methodology and Resources/Active Directory Attack.md
SpiderLabs' version of Responder is deprecated (per its README) so I updated link to the lgandx version. Also I added InveighZero which is a great Windows alternative for Responder.
=> Updated Responder link and added InveighZero

Methodology and Resources/Methodology and enumeration.md
Querying the Wayback Machine from the CLI is pretty helpful during recon.
=> Added cURL command for Wayback Machine querying

Methodology and Resources/Network Pivoting Techniques.md
bitrot.sh domain is expired and hence the link in the markdown file was broken.
=> Removed broken link

API Key Leaks/README.md, Account Takeover/README.md, Insecure Source Code Management/README.md, Kubernetes/readme.md, Methodology and Resources/Active Directory Attack.md, Methodology and Resources/Cloud - AWS Pentest.md, Methodology and Resources/Network Discovery.md, Methodology and Resources/Windows - Mimikatz.md, Open Redirect/README.md, SQL Injection/README.md, Server Side Template Injection/README.md, Web Cache Deception/README.md, XSS Injection/README.md, XXE Injection/Files/XXE PHP Wrapper.xml, XXE Injection/README.md
Fixing typos in the repository's documentation.
Basically, I ran the following command to spot typos: 
```
find . -type f | grep README | sed -e 's/\ /\\\ /g' | xargs cat | aspell list -d en_US --add-wordlists=exclusions.txt
``` 
With **exclusions.txt** being a file I progressively updated to filter out words in other languages than English, intentional "mistakes" (or now commonly used misspelled words like [referer](https://english.stackexchange.com/questions/42630/referer-or-referrer/42636)), and others.
=> Fix(Docs): Correcting typos on the repo

File Inclusion/README.md
Specifying alternative access method through SSH since SSH is assumed to be running on the Linux machine. Read id_rsa for that user to obtain the SSH private key.
=> Specifying alternative access method through SSH

Server Side Request Forgery/README.md
The netdoc section has gohper scheme which is wrong and i have corrected with the right payload and also added blind ssrf payloads using jar protocol which is only supported in java applications
=> Update ssrf payloads specific to java 

SQL Injection/SQLite Injection.md
Since we retrieve only the rows with a specific table name `name ='table_name', the table name won't start with `sqlite_` .
Thus, we can remove the unnecessary condition.
=> Remove unnecessary condition to extract columns

Account Takeover/README.md
The HackerOne reports mentioned in this doc are referring to Request Smuggling, not CSRF
=> Puts the H1 reports at the right place

Methodology and Resources/Active Directory Attack.md
There is a small typo in Methodology and Resources/Active Directory Attack.md.
Should read `account` rather than `accound`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, accound -> account

Request Smuggling/README.md
PortSwigger published a more recent article on protocol smuggling which is worth adding the the Reference section IMO
=> Add PortSwigger http-desync reborn article

Methodology and Resources/Reverse Shell Cheatsheet.md
Some embedded systems like busybox won't have mkfifo present; instead, they will have mknod. This updated code can spawn reverse shell in systems that use mknod instead of mkfifo.
=> Added Netcat BusyBox

Methodology and Resources/Reverse Shell Cheatsheet.md
Now the reverse shell supports the "cd" command and maintains persistence when an error is raised.
=> Improve Ruby reverse shell

XXE Injection/README.md
Hi,
while testing for XXEs in SVG I needed to make some changes so that the payloads are treated as valid XMLs. I thought it's worth doing a pr so that nobody misses an XXE because of lack of required attribute.
I fixed 2 things actually:
I was validating my payloads [here](https://validator.w3.org/#validate_by_input+with_options) and when you use _Validate by Direct Input_, choose _SVG 1.1_ DOCTYPE and paste 
```xml
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="300" version="1.1" height="200">
<image xlink:href="expect://ls"></image>
</svg>
```
There are 2 errors:
> Line 2, Column 36: required attribute "width" not specified 
> \<image xlink:href="expect://ls">\</image>
> The attribute given above is required for an element that you've used, …
=> improved XXE SVG payloads to be valid XMLs

Server Side Template Injection/README.md
- Added context-free jinja2 payloads to access the os module in SSTI exploitation
- Fixed a few typos and broken links
- https://twitter.com/podalirius_/status/1420072160450785280 
- https://podalirius.net/en/articles/python-vulnerabilities-code-execution-in-jinja-templates/
=> Added context-free jinja2 payloads

SQL Injection/MSSQL Injection.md
MSSQL 2017+ has an useful function called `STRING_AGG()` which I'd say is the most equivalent to `GROUP_CONCAT()` in another well known DMBS such as MySQL I find this approach makes the output not only cleaner, but also avoids you having to use other methods such as `ORDER BY name OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY` or anything along the lines of that where you have to specify `offset` or `limit` equivalent to MSSQL which is a lot more convoluted than it needs to be.
For this instance, I'm running a mssql docker container for ease of use and I do not have a windows installation ready, but this should and will work on MSSQL.
```sh
root@28153f762ac3:/# /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P toor123! -q "SELECT STRING_AGG(name, ', ') FROM master..sysdatabases;"
master, tempdb, …
```
=> GROUP_CONCAT equivelent for MSSQL

XSS Injection/README.md
Hi, i recently came accross the payload for CSP bypasses using the scheme-src `data`. I think that the current payload is unnecessary complex in regards of the actuall issue of the vulnerable CSP. Therefore i would propose to change the payload to the most bare needed complexity and add the mozzilla documentation to it, where the issue is also stated:
```
<scheme-source>
data: Allows data: URIs to be used as a content source. This is insecure; an attacker can also inject arbitrary data: URIs. Use this sparingly and definitely not for scripts.
```
=> XSS: Remove unnecessary complexity from CSP bypass payload

SQL Injection/SQLite Injection.md
Fixing the payload in the  "RCE  - Attach Database" section of `SQL Injection/SQLite Injection.md`
The old payload doesn't work for many cases as the `php` in `<?php` is missing.
=> Update SQL Injection/SQLite Injection.md

Command Injection/README.md
This PR adds two use cases where spaces (`0x20`) and braces (`{ }`) are removed from a payload.
=> Command Injection space alternatives

Methodology and Resources/Reverse Shell Cheatsheet.md
For the first time there is no `/tmp/f` so `rm` will throw an error. Fixing it by adding `-f` to `rm` command
=> Fix rm bug in netcat reverseshell on OpenBSD & BusyBox

XSS Injection/XSS in Angular.md
Added payload which executes without any usage of (')single-quotes or (")double-quotes.
Proof of payload:
```
https://portswigger-labs.net/xss/angularjs.php?type=reflected&csp=0&version=1.6.0&x={{x=767015343;y=50986827;a=x.toString(36)%2by.toString(36);b={};a.sub.call.call(b[a].getOwnPropertyDescriptor(b[a].getPrototypeOf(a.sub),a).value,0,toString()[a].fromCharCode(112,114,111,109,112,116,40,100,111,99,117,109,101,110,116,46,100,111,109,97,105,110,41))()}}
https://portswigger-labs.net/xss/angularjs.php?type=reflected&csp=0&version=1.6.0&x={{x=767015343;y=50986827;a=x.toString(36)%2by.toString(36);b={};a.sub.call.call(b[a].getOwnPropertyDescriptor(b[a].getPrototypeOf(a.sub),a).value,0,toString()[a].fromCodePoint(112,114,111,109,112,116,40,100,111,99,117,109,101,110,116,46,100,111,109,97,10 …
```
=> [update] Angular XSS payload

Server Side Request Forgery/README.md
307 and 308 redirects can be helpful when needing to send a POST request to a target while bypassing restrictions using redirection.
=> Added information on 307 and 308 redirects

NoSQL Injection/README.md
`https://www.owasp.org/index.php/Testing_for_NoSQL_injection` to `https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/07-Input_Validation_Testing/05.6-Testing_for_NoSQL_Injection`
Click the `Testing for NoSQL injection - OWASP` link to move it to the SQL Injection item in OWASP. WSTG has the same NoSQL Injection document, so I changed it to that link.
=> Update References link in NoSQL Injection

SQL Injection/OracleSQL Injection.md
missing 'T' in the SELECT in the  Oracle blind SQLI section
=> Update OracleSQL Injection.md

Server Side Template Injection/README.md
Was very unsuccessful with the given Twig examples, quotes were escaped so got invalid, file_excerpt threw an error, too. Include() and also injecting the file name helped. Don't know if this is a wordpress thing...
=> Twig in Wordpress

CSRF Injection/README.md
This pull adds a technique for sending multipart/form-data requests with upload files in CSRF / reflected XSS attacks. Useful for CSRF file upload or for popping reflected XSS in filename/filecontent parameters
=> Add multipart/form-data CSRF technique

Methodology and Resources/Active Directory Attack.md
Not sure if it is deprecated but by tackling the box Outdated on HTB, the command didn't worked with two `&&`. To concatenate  `"net user WSUSDemo Password123! /add ` and `net localgroup administrators WSUSDemo /add\""`, the `^&` is required.
=> Quick fix for WSUS malicious patch

Insecure Deserialization/Ruby.md
Currently listed gadget chain has been patched, however a new one was discovered, as per: https://staaldraad.github.io/post/2021-01-09-universal-rce-ruby-yaml-load-updated/
=> Add new ruby yaml gadget chain

Methodology and Resources/Windows - Mimikatz.md
Hekatomb is a python script that connects to LDAP directory to retrieve all computers and users informations. Then it will download all DPAPI blob of all users from all computers. Finally, it will extract domain controller private key through RPC uses it to decrypt all credentials.
More infos here : https://github.com/Processus-Thief/HEKATOMB
=> Adding Hekatomb.py to DPAPI credentials stealing

API Key Leaks/README.md
This will add [Trivy](https://github.com/aquasecurity/trivy) to the tools section of the topic `Api Key Leaks`. This is currently my go-to tool to scan docker images or repositories for secrets and therefore should be mentioned. As I could not see it mentioned somewhere, I picked this topic as it seemed to fit best. But it might also fit for other topics such as scanning for vulnerable dependencies (CVE) used in a projects or weaknesses in regards of SBOM/IaC. If you see a better fit for Trivy at other topics or might want to add it redundantly multiple times I guess we could add it to this MR.
Let me know what you think. :)
(Also changed the phrasing for two other tools as their main repository uses the upper/lowecase as changed which should not require a separate MR)
=> Api Key Leaks: Add Trivy to tools section

Java RMI/README.md
This PR will add remote-method-guesser as tool. I also changed the overall structure of the previous article keeping most of the content but adjusting it to the layout mentioned in CONTRIBUTION.md
I thing rmg is a great addition to the landscape of RMI exploitation and definitely belongs to the article. Let me know if you have any objections or prefer other changes.
=> Java RMI: Add remote-method-guesser to tools

CVE Exploits/README.md
This will add the trickiest CVE repository to the CVE Exploits section. Since the section of this topic kinda differs to the other topics I did not additionally add a Summary, if you would like to have it let me know and I can sort it out.
Nevertheless, I think that the trickest CVE repository is a really nice addition to quickly asses known CVE's for known PoC's since the list will be updated on a regular basis automatically.
=> CVE Exploit: Add trickest CVE repo

Methodology and Resources/Linux - Evasion.md, Methodology and Resources/Linux - Persistence.md, README.md
Linux evasion techniques were previously included as part of persistence, but the number of techniques are varied enough where it likely should be its own article.  (I'm planning to submit an additional PR after this to expand on the existing techniques and to include additional ones.  Adding them all to the persistence page would make it too bulky.)
=> Add Linux evasion to its own article

Request Smuggling/README.md
I've tried to give a brief (and certainly not exhaustive) summary of what HTTP request smuggling actually is, HTTP/2 request smuggling attacks and James Kettle's new research on client-side desync attacks.
Hopefully this is a useful level of simplification; I'm happy to elaborate more or less if anyone has suggestions, or to close this completely if this isn't enough of a 'payload' to fit here (I figured it counts as the 'techniques' - but it seems like )
=> Adds more details to the HTTP request smuggling topic

Server Side Template Injection/README.md
Changed name in summary links: Django Template > Django Templates
Fixed corresponding link: #django-template > #django-templates
=> Fix: Broken Link

Command Injection/README.md
Example of using nohup and & to run a command that won't be killed by, e.g. a PHP timeout.
=> feat: Backgrounding long running commands

Methodology and Resources/Active Directory Attack.md
Relative github link `Cloud%20-%20Azure%20Pentest.md/#azure-recon-tools` is converted with MkDocs to:
```
https://swisskyrepo.github.io/PayloadsAllTheThingsWeb/Methodology%20and%20Resources/Active%20Directory%20Attack/Cloud%20-%20Azure%20Pentest.md/#azure-recon-tools
```
Instead of
```
https://swisskyrepo.github.io/PayloadsAllTheThingsWeb/Methodology%20and%20Resources/Cloud%20-%20Azure%20Pentest/#azure-recon-tools
```
A fix on this could be interesting. We could even go further and convert automatically links in .md files such as `https://github.com/swisskyrepo/PayloadsAllTheThings/` to `https://swisskyrepo.github.io/PayloadsAllTheThingsWeb`.
=> Fix broken link not compatible with MkDocs

Methodology and Resources/Metasploit - Cheatsheet.md
Hello,
This is my contribution to your repo.
In fact, there are two errors in my opinion:
- You don't need sudo to use docker
- The docker image is no longer available ([see yourself](https://hub.docker.com/search?q=remnux%2Fmetasploit))
Like they say to use their installers, I propose not to use the docker image. <https://github.com/rapid7/metasploit-framework>
I'm not an expert on Metasploit, so feel free to ask questions.
=> fix: remove docker metasploit installation

Web Sockets/README.md
It seems, that the blog post for the first reference is no longer present. I therefore added a version from archive.org which seemingly still contains most images.
I added the Hacktricks article for CSWSH as reference also.
=> Web Sockets: Update README.md

Server Side Template Injection/README.md
Pen-testers I work with have discovered these filters can be used to retrieve sensitive system information.
=> Added Twig 'passthru' filter exploits

SQL Injection/SQLite Injection.md
add "group_concat" so that all tables can be extracted once if the injectable query only returns one item
=> Update SQLite Injection.md

AWS Amazon Bucket S3/README.md
**PR Summary**:
PR simply fixes the broken link to the `move-a-file-into-the-bucket` section inside the `AWS Amazon Bucket S3/README.md` file. Relevant page can be found [here](https://swisskyrepo.github.io/PayloadsAllTheThings/AWS%20Amazon%20Bucket%20S3/).
=> fix: broken link on AWS Amazon Bucket S3 page

Methodology and Resources/Reverse Shell Cheatsheet.md
From [stackoverflow](https://stackoverflow.com/questions/48958814/what-is-the-rust-equivalent-of-a-reverse-shell-script-written-in-python?answertab=active#tab-top). 
It works fine
=> feat: Add Rust reverse shell for unix

Methodology and Resources/Active Directory Attack.md
This commit add a Kerberoasting technique without domain account/credentials just a user without pre-authentication (AS_REP Roastable)
=> Add Kerberoasting w/o domain account

Methodology and Resources/Cloud - AWS Pentest.md
Cognito Scanner is a CLI open-source tool. It enables to pentest Cognito AWS instance easily. It can be installed through a python package
=> feat: add cognito-scanner tool for AWS pentest

CSRF Injection/README.md
Add JSON simple paylaod with autosubmit form. Using autosubmit form instead of AJax, allow to bypass some protection like the Standard Enhanced Tracking Protection in Firfefox, which will refuse to send cookie with  cross-site  Ajax request (tested with Firefox 115.0.2esr),.
=> Add JSON simple with form

LaTeX Injection/README.md
By solving the hackthebox machine "topology" I came across this latex injection blacklist bypass.
More information can be found here:
https://agiletribe.wordpress.com/2015/04/07/adding-unicode-characters-to-latex-documents/
=> latex injection add blacklist bypass

XSS Injection/XSS in Angular.md
Indicate that ng-app in a root element is needed to inject Angular JS template. Injecting below payload without a root element with ng-app will not result in a successful injection
=> specify condition to perform Angular JS Injection

Prototype Pollution/README.md
Somtimes `__proto__` property may not work, so adding the payload for Polluting the prototype via the `constructor` property in JSON input
=> adding the payload for Polluting the prototype via the `constructor`  property in JSON input

Server Side Request Forgery/README.md
Hey Swissky, adding Hetzner Metadata
Details: https://docs.hetzner.cloud/#server-metadata
=> Adding Hetzner Cloud Metadata URL

XSS Injection/README.md
On multiple occasions I was able to toy around with email address validators that implement the RFC5322 syntax rules.
https://pkg.go.dev/net/mail#ParseAddress is one such instance where XSS (or HTML injection payloads) may pass through :)
Feel free to merge or alter descriptions as you see fit.
=> Add additional XSS payload in email addresses RFC5322

XSS Injection/Intruders/xss_alert_identifiable.txt
same as 'xss_alert.txt', but with identifiable payloads, e.g. alert(1992) instead of just alert(1). This is useful in case of stored xss, when you inject all the payloads and then need to identify which payloads were successful.
=> added 'xss_alert_identifiable.txt'

File Inclusion/README.md
Vuln discovery/exploit techniques
- Filter, File, Data, Input, Expect wrappers
- Remote File Inclusion
- Path Traversal
- Command injection
- Heuristic (Reflected XSS, HTMLi, CRLF, error disclosure) checks
Features
- Exploit RCEs automatically to reverse shell (custom built shell)
- Second order (blind) vulnerability support - Blind Command injection, stored XSS, second order LFI
- Full control over the HTTP requests sent (Specify headers, GET, request body/POST, method)
- Ability to test arbitrary part of the request (headers, POST, URL parameters)
- Ability to test multiple URLs at once, or test single raw request from a file
- Timeout and time in between requests
- Pivot requests through proxy
- Payload manipulation options
- Many more options and features
=> Add LFImap tool

Type Juggling/README.md
The example `'0x1234Ab' == '1193131'` on the true statements section doesnt't work for versions equal or after PHP7, it just returns false.
=> Fixed not working example

Server Side Request Forgery/README.md
I've created redirection service named r3dir which works similar to Burp Collaborator and https://1u.ms tools. Here an article which explains how to use it https://www.leviathansecurity.com/blog/bypassing-ssrf-filters-using-r3dir. Also I have added several simple examples.
=> Adding r3dir tool to SSRF README.md 

SQL Injection/PostgreSQL Injection.md
I have added a query for retrieving current user table-level privileges while excluding system schemas (pg_catalog and information_schema). Additionally, I removed the usecatupd column from the pg_user query as it is dependent on older PostgreSQL versions.
Thanks for maintaining this repo
=> PostgreSQL privilege list update

Client Side Path Traversal/README.md
Hello,
I've just add an other case for CSPT2CSRF real world scenarios.
Thanks for your work and your awesome repo !
=> Add CVE-2023–5123 in CSPT2CSRF real world scenario

XXE Injection/README.md
-r flag is needed to include sub directories in the final archive
```bash
$ zip -u
```
```bash
adding: [Content_Types].xml (deflated 77%)
adding: docProps/ (stored 0%)
adding: _rels/ (stored 0%)
adding: xl/ (stored 0%)
```
```bash
$ zip -r -u
```
```bash
adding: [Content_Types].xml (deflated 77%)
adding: docProps/ (stored 0%)
adding: docProps/custom.xml (deflated 37%)
adding: docProps/core.xml (deflated 51%)
adding: docProps/app.xml (deflated 39%)
adding: _rels/ (stored 0%)
adding: _rels/.rels (deflated 67%)
adding: xl/ (stored 0%)
adding: xl/worksheets/ (stored 0%)
adding: xl/worksheets/sheet1.xml (deflated 71%)
adding: xl/workbook.xml (deflated 43%)
adding: xl/sharedStrings.xml (deflated 87%)
adding: xl/theme/ (stored 0%)
adding: xl/theme/theme1.xml (deflated 76%)
adding: xl/_rels/ …
```
=> Add missing -r flag for xxe excel file rebuilding with zip command

SQL Injection/MySQL Injection.md
Removed extra parentheses in the “Using Conditional Statements” section of MySQL Injection.md.
=> Fix extra parentheses in MySQL Injection.md

SQL Injection/Intruder/Generic_TimeBased.txt
Add support for `||` (concatenation) operator in PostgreSQL
=> Add support for `||` (concatenation) operator in PostgreSQL for time based SQL injection

Server Side Template Injection/Java.md
Hi @swisskyrepo ,
While working with Velocity template SSTI, I encountered some challenges finding reliable payloads. To help others facing similar issues, I’ve added a more robust example that supports base64-encoded command execution.
Hope this addition proves useful!
Best regards,
=> Add Velocity SSTI payloads with base64 command support

Methodology and Resources/Web Attack Surface.md
Hi,
**Fixed:**
- Missing path - added `/blob/main/docs/`
As there is no `issues` tab, a short description about the problem.
**Repro steps:**
1. Visit https://github.com/swisskyrepo/PayloadsAllTheThings/blob/master/Methodology%20and%20Resources/Web%20Attack%20Surface.md
2. Notice "⚠️ Content of this page has been moved to InternalAllTheThings/redteam/access/web-attack-surface" with invalid link `https://github.com/swisskyrepo/InternalAllTheThings/redteam/access/web-attack-surface`
**Screenshot**
Current view - `error 404` page:
It is changed / updated to valid link:
https://github.com/swisskyrepo/InternalAllTheThings/blob/main/docs/redteam/access/web-attack-surface.md
View after fix:
I was little confused for a while. This PR should implement the fix.
Best wishes,
=> Update Web Attack Surface.md
